# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: false
      settings:
        MinVersion: '10.0.22631'

  resources:

    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: false
      settings:
        Ensure: Present

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: visualStudioCodePackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: gitPackage
      directives:
        description: Install Git
        allowPrerelease: false
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: NETSDK9Package
      directives:
        description: Install .NET SDK 9
        allowPrerelease: false
      settings:
        id: Microsoft.DotNet.SDK.9
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powerShellPackage
      directives:
        description: Install PowerShell
        allowPrerelease: false
      settings:
        id: Microsoft.PowerShell
        source: winget

  configurationVersion: 0.2.0
